yarnPath: .yarn/releases/yarn-3.6.1.cjs

packageExtensions:
  ts-loader@*:
    dependencies:
      webpack: "*"

  "@nestjs/passport@*":
    dependencies:
      passport: "*"

  "@nestjs/axios@*":
    dependencies:
      axios: "*"
